/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.shgbit.card;

import java.io.IOException;

import com.fazecast.jSerialComm.*;

public class App {
  public void run() throws IOException {
    String portName = "/dev/tty.usbserial-14310";
    SerialPort comPort = SerialPort.getCommPort(portName);
    // SerialPort comPort = SerialPort.getCommPorts()[4];
    comPort.setBaudRate(9600);
    comPort.setComPortTimeouts(SerialPort.TIMEOUT_READ_SEMI_BLOCKING, 0, 0);
    comPort.openPort();

    if (!comPort.isOpen()) {
      throw new IOException();
    }

    try {
      while (true) {
        byte[] readBuffer = new byte[1024];
        int numRead = comPort.readBytes(readBuffer, readBuffer.length);
        // System.out.println("Read " + numRead + " bytes.");
        System.out.println(new String(readBuffer, 0, numRead));
      }
    } catch (Exception e) {
      System.out.println(">>>");
      e.printStackTrace();
    }
    comPort.closePort();
  }

  public static void main(String[] args) throws IOException {
    new App().run();
  }
}
